ls:
  src:
    # .dir: kebab-case
    # .d.ts: kebab-case
    # .js: kebab-case
    # .ts: kebab-case

    components:
      # .dir: PascalCase
      # .ts: regex:Schema(([A-Z])\w+.(hooks|props)\w+]+)
      .module.scss: pascalcase
      .hooks.tsx: pascalcase
      .spec.tsx: pascalcase
      .tsx: pascalcase

ignore:
  - node_modules
